version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  reservations-service:
    build: ./services/reservations-service
    container_name: reservations-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: reservations_db
      DB_PORT: 5432
      RABBITMQ_URL: amqp://rabbitmq:5672
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm start

  notifications-service:
    build: ./services/notifications-service
    container_name: notifications-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672

